### PR TITLE
Request feature validation while indexing

### PR DESCRIPTION
**Pull request by springmeyer**
Adds the `--validate-features` to `mapnik-index` as per https://github.com/mapnik/mapnik/issues/3170

/cc @GretaCB @artemp

### CODE REVIEW

**Comment by springmeyer** [comment]
TODO before merging:

 - [ ] add test coverage for an invalid json that triggers an error with this option (and presumably does not trigger an error without the option)

**Comment by GretaCB** [comment]
@springmeyer This seems like an added feature (as does `geojsonhint`), and I think [handling the the `Failed to parse geojson feature` error](https://github.com/mapbox/unpacker/issues/700#issuecomment-162717412) should be included in the `mapnik-index` unpacker deploy and take precedence over this feature for now.

But this is pretty much ready when the time comes. I just want to iterate through these all these changes instead of in a huge chunk.

**Comment by springmeyer** [comment]
@GretaCB sounds good to stage things and work to integrate this as a followup.

**Comment by GretaCB** [comment]
Merged to https://github.com/mapbox/preprocessorcerer/pull/60. Closing.

**Pull request closed without merging**
